# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(630, 491)
        self.formLayout = QtWidgets.QFormLayout(Form)
        self.formLayout.setObjectName("formLayout")
        self.btn = QtWidgets.QPushButton(Form)
        self.btn.setObjectName("btn")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.btn)
        self.textInput = QtWidgets.QLineEdit(Form)
        self.textInput.setObjectName("textInput")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.textInput)
        self.textOutput = QtWidgets.QTextBrowser(Form)
        self.textOutput.setObjectName("textOutput")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.textOutput)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "藏头诗生成器"))
        self.btn.setText(_translate("Form", "生成"))
