# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(630, 491)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textInput = QtWidgets.QLineEdit(Form)
        self.textInput.setObjectName("textInput")
        self.horizontalLayout.addWidget(self.textInput)
        self.btn = QtWidgets.QPushButton(Form)
        self.btn.setObjectName("btn")
        self.horizontalLayout.addWidget(self.btn)
        self.modeHelperLabel = QtWidgets.QLabel(Form)
        self.modeHelperLabel.setObjectName("modeHelperLabel")
        self.horizontalLayout.addWidget(self.modeHelperLabel)
        self.modeLabel = QtWidgets.QLabel(Form)
        self.modeLabel.setObjectName("modeLabel")
        self.horizontalLayout.addWidget(self.modeLabel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.textOutput = QtWidgets.QTextBrowser(Form)
        self.textOutput.setObjectName("textOutput")
        self.verticalLayout.addWidget(self.textOutput)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "藏头诗生成器"))
        self.btn.setText(_translate("Form", "生成"))
        self.modeHelperLabel.setText(_translate("Form", "模式："))
        self.modeLabel.setText(_translate("Form", "未知"))
